### ISSUE TITLE
Can the type of the computer property be an Interface?

### ISSUE THREAD

**Issue by paulvanbladel** [hazzik/DelegateDecompiler#127] opened 2018-07-22 18:13 UTC
I have following use case.
An Order type which has a computed property "OrderStatus" of type IOrderStatus:
```
 [Computed]
 [NotMapped]
        public IOrderStatus OrderStatus
        {
            get
            {
                return (_orderStatus == "Draft") ? (IOrderStatus)(new Draft()) : (IOrderStatus)(new Ordered());
            }
        }
```
Now I want to query as follows:
```
 var result = _context.Orders
                  .Where(c => c.OrderStatus is Draft)
                  .Decompile()
                  .ToList();
```
When NOT using .Decompile I get the correct results but the query is done locally (that's why I'm using DelegateDecompiler :) )

but with .Decompile() I get as error: : 'Argument types do not match'

Any idea?

**Comment by magicmoux** [comment] 2018-07-25 13:33
Could you please provide a more complete code example for tests and potential fix ?

Thanks,
Max.

**Comment by hazzik** [comment] 2022-10-20 04:55
Duplicate of #107

**Closed by hazzik** 2022-10-20 04:55 UTC
Labels: bug
