### ISSUE TITLE
DecompileExpressionVisitor.VisitMethodCall with virtual computed methods

### ISSUE THREAD

**Issue by magicmoux** [hazzik/DelegateDecompiler#113] opened 2017-12-17 09:40 UTC
Hi people,

first a big thank you for making this library, it promises so much potential when dealing with EF or other providers' limitations.

However, I found out a "bug" in the native LINQ implementation that do not return the most specific MethodInfo when visiting method calls.

Here's a simple test to see the issue : 

`    

        [TestFixture]
        public class VirtualMemberTest : DecompilerTestsBase
        {
        private abstract class BaseClass
        {
            public int Property { get; set; }

            [Computed]
            public virtual int GetTotal()
            {
                return Property;
            }
        }

        private class ConcreteClass
            : BaseClass
        {
            public int OtherProperty { get; set; }

            [Computed]
            public override int GetTotal()
            {
                return base.GetTotal() + OtherProperty;
            }
        }

        [Test]
        public void DecompileOveriddenMemberWithBaseCall()
        {
            Expression<Func<ConcreteClass, int>> expected = x => x.Property + x.OtherProperty;
            Expression<Func<ConcreteClass, int>> compiled = x => x.GetTotal();
            var result = DecompileExpressionVisitor.Decompile(compiled); // returns "x => x.Property"
            Assert.AreEqual(expected.ToString(), result.ToString());
        }
        }
`

I'm currently working in my personnal fork on a workaround (
https://github.com/magicmoux/DelegateDecompiler/commit/c10a43315f84c0d0a68797948924a02dc3d80e5b)
It seems to fix the problem but still requires some work before being submitted as a PR so could you check it to tell me if it seems a sensible approach ?

Thanks in advance

**Comment by magicmoux** [comment] 2017-12-17 09:51
Fix visible at
https://github.com/magicmoux/DelegateDecompiler/commit/c10a43315f84c0d0a68797948924a02dc3d80e5b

**Comment by magicmoux** [comment] 2017-12-18 13:01
Hi again, 
I provide a solution to this issue with PR https://github.com/hazzik/DelegateDecompiler/pull/114

**Comment by hazzik** [comment] 2018-04-28 09:14
Duplicate of #76

**Closed by hazzik** 2018-04-28 09:14 UTC
